apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  # this is base64 encoded.
  # this is still bad. if you have confidential data and you commit to github. but better then config maps
  database_url: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGxvY2FsaG9zdDo1NDMzL2s4cwo="